### ISSUE TITLE
Demande d'admission et d' ajout du grade sheriff

### ISSUE THREAD

**Issue by CDK-Github** [gta-lcrp/lcrp-tracker#12]
Submitter: Jim Marshall
Email: frwarlockgaming@gmail.com
J'aimerai améliorer le RP de mon personnage en le faisant passer sherif ,c'est a dire plus de patrouille en dehors de la ville (sandy shores et blane country).

J'en ai parlé avec Luchiano et il est d'accord. Il a dit qu'il allait s'occuper de changer le nom d'un grade . 
ma seule demande est si possible d'avoir une tenue de shérif (celle du jeux ou si s'est pas possible un mod, pour améliorer le gameplay ) 

Merci d'avance.

**Comment by POUTINENagrom** [comment]
Non pas de police du nord et police du sud
On en reparlera quand il y aura juste une police en ville
et quel fait sont travail comme ça doit être fait
