### ISSUE TITLE
Les permis 

### ISSUE THREAD

**Issue by CDK-Github** [gta-lcrp/lcrp-tracker#13]
Submitter: Hugo Starks
Email: hugo77640@gmail.com
j'ai brau passer plusieur fois les permis je n'ai pas l'item du coup je c'est jamais si je l'ai ou pas

**Comment by POUTINENagrom** [comment]
un conflit est present entre le permis de conduire et le job ambulance qui gere la mort ou le coma ce conflit sera gere au moment des 64 slots avant risque de mettre en peril la stabilité global du serveur patience
