### ISSUE TITLE
Bug blanchiment

### ISSUE THREAD

**Issue by CDK-Github** [gta-lcrp/lcrp-tracker#5]
Submitter: Lorenzo Luciano
Bonjour 
Je suis patron Mecano sur le serveur confrérie 2 et hier vers 23h-0h on m'as
donné 750 000$ a blanchir plusieurs heures IG après il n'était toujours pas 
blanchi et plus de 24h après toujours rien.
Voila si éventuellement vous pouvez rembourser et surtout prendre en compte le problème 
pour éviter ce genre de souci a l'avenir. 
Cordialement, je reste dispo discord si il y a besoin de détails.

**Comment by POUTINENagrom** [comment]
probleme regler la source etait au niveau de esx society le wash ne coordonnée pas avec le compte entreprise
